version: '3.8'

services:
  zookeeper-invoice:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper-invoice
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2182"
    networks:
      - finance-network
    volumes:
      - zookeeper-data-invoice:/var/lib/zookeeper

  kafka-invoice:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-invoice
    depends_on:
      - zookeeper-invoice
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-invoice:2182
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-invoice:29093,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9093:9093"
    networks:
      - finance-network
    volumes:
      - kafka-data-invoice:/var/lib/kafka/data

  postgres-salesinvoicedb:
    image: postgres:15-alpine
    container_name: postgres-salesinvoicedb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: salesinvoicedb
    volumes:
      - postgres-salesinvoice-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - finance-network

  salesinvoice-service:
    build:
      context: .
      dockerfile: src/main/Dockerfile
    container_name: salesinvoice-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-salesinvoicedb:5432/salesinvoicedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-invoice:29093
    networks:
      - finance-network

  sales-invoice-client:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: salesinvoice-client
    ports:
      - "3001:80"
    networks:
      - finance-network

networks:
  finance-network:
    external: true

volumes:
  postgres-salesinvoice-data:
  kafka-data-invoice:
  zookeeper-data-invoice:
